"""Correction Learning models — CEO edits that teach BEE the user's style.

When the CEO edits an ExecutionArtifact (email draft, meeting agenda, etc.),
the ``CorrectionLearningService`` captures the diff, extracts style rules, and
updates the ``UserStyleProfile``. Future artifact generations automatically
incorporate these learned preferences without any manual configuration.

Learning mechanism
------------------
1. ``ArtifactCorrection`` stores the raw before/after edit with extracted diff ops.
2. ``StyleRule`` represents a single learned preference (e.g., "avoid_social_opener")
   with a confidence weight that grows as the CEO confirms the same pattern.
3. ``UserStyleProfile`` accumulates all rules into a synthesised prompt injection
   that ``ExecutiveAgent`` prepends to every generation call.

Self-learning without configuration
------------------------------------
The system uses a weighted moving average: each new correction nudges existing
rules toward higher/lower confidence without replacing them. A rule is promoted
to "authoritative" (weight ≥ 0.80) after being confirmed ≥ 3 times.
Authoritative rules are included in the style_summary injected into prompts.

Design: one ``UserStyleProfile`` per BEE installation (the CEO). Each artifact
type (email_draft, meeting_agenda, linkedin_message) has its own rule set so
the CEO's email style is separate from their LinkedIn style.
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import JSON, Column
from sqlmodel import Field

from app.models.base import TimestampMixin, new_uuid


class DiffOpType(str):
    DELETE = "delete"        # CEO removed this segment
    SHORTEN = "shorten"      # CEO shortened this segment
    EXPAND = "expand"        # CEO added content
    REWRITE = "rewrite"      # CEO replaced with different content
    KEEP = "keep"            # CEO kept unchanged (positive signal)
    REORDER = "reorder"      # CEO moved segments around


class StyleRuleType(str):
    """Detected writing style preferences."""

    # Opening / tone
    AVOID_SOCIAL_OPENER = "avoid_social_opener"          # "Hope you're well" → deleted
    PREFER_DIRECT_OPENER = "prefer_direct_opener"         # Jumps to value immediately
    AVOID_FILLER_PHRASES = "avoid_filler_phrases"         # "Just wanted to reach out" → deleted

    # Content structure
    PREFER_BULLET_POINTS = "prefer_bullet_points"         # Formats as bullet list
    PREFER_SHORT_PARAGRAPHS = "prefer_short_paragraphs"   # Breaks long paragraphs
    PREFER_DATA_EVIDENCE = "prefer_data_evidence"         # Adds stats/metrics
    PREFER_STORYTELLING = "prefer_storytelling"           # Adds narrative examples

    # Length
    PREFER_CONCISE = "prefer_concise"                     # Significantly shortened
    PREFER_DETAILED = "prefer_detailed"                   # Significantly expanded

    # CTA (Call to Action)
    PREFER_SOFT_CTA = "prefer_soft_cta"                   # "Would love your thoughts"
    PREFER_DIRECT_CTA = "prefer_direct_cta"               # "Let's schedule 30 min"

    # Closing
    AVOID_FORMAL_CLOSING = "avoid_formal_closing"         # Removed "Kind regards" etc.
    PREFER_CASUAL_CLOSING = "prefer_casual_closing"       # Added first-name sign-off

    # Personalization
    PREFER_COMPANY_SPECIFICS = "prefer_company_specifics" # Added company-specific details
    AVOID_GENERIC_CLAIMS = "avoid_generic_claims"          # Removed "industry-leading" etc.


class ArtifactCorrection(TimestampMixin, table=True):
    """A single CEO correction event on a generated artifact.

    Records the before/after content and the extracted diff operations.
    Each correction feeds the ``PromptAdjustmentEngine`` to update style rules.
    """

    __tablename__ = "artifact_corrections"

    id: uuid.UUID = Field(default_factory=new_uuid, primary_key=True, index=True)

    # ── Traceability ──────────────────────────────────────────────────────────
    opportunity_id: uuid.UUID | None = Field(default=None, index=True)
    lead_id: uuid.UUID | None = Field(default=None, index=True)
    artifact_type: str = Field(index=True, description="email_draft | meeting_agenda | linkedin_message | next_steps")
    generator_name: str | None = Field(default=None, description="Which generator produced the original content")

    # ── The edit ─────────────────────────────────────────────────────────────
    original_content: str = Field(description="Content as generated by BEE")
    edited_content: str = Field(description="Content after CEO edits")

    # ── Extracted intelligence ────────────────────────────────────────────────
    diff_ops: list[dict[str, Any]] = Field(
        default_factory=list,
        sa_column=Column(JSON),
        description="Structured list of {type, content, position} diff operations",
    )
    extracted_rules: list[str] = Field(
        default_factory=list,
        sa_column=Column(JSON),
        description="StyleRuleType values extracted from this correction",
    )
    change_ratio: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Proportion of original content that was changed (0=no change, 1=full rewrite)",
    )

    # ── Context at correction time ────────────────────────────────────────────
    psychographic_style: str | None = Field(default=None, description="DISC style of the lead at correction time")
    channel: str | None = Field(default=None, description="Channel context (email, linkedin, etc.)")


class UserStyleProfile(TimestampMixin, table=True):
    """Accumulated CEO writing style preferences across all corrections.

    There is exactly ONE active UserStyleProfile per BEE installation.
    Each artifact type stores its own rules so email ≠ LinkedIn ≠ meeting style.

    The ``style_summary`` field is a ready-to-inject prompt fragment:
    "CEO writing preferences: avoid social openers (high confidence),
     prefer bullet points (medium confidence), direct CTA (high confidence)."

    This is prepended to every ExecutiveAgent generation call automatically.
    """

    __tablename__ = "user_style_profiles"

    id: uuid.UUID = Field(default_factory=new_uuid, primary_key=True, index=True)

    # ── Accumulated rules per artifact type ──────────────────────────────────
    # Dict: artifact_type → { rule_type → {weight, confirmation_count, last_seen} }
    rules: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSON),
        description="Nested dict of artifact_type → rule_type → {weight, count, last_seen}",
    )

    # ── Synthesised prompt injection ──────────────────────────────────────────
    style_summary: str = Field(
        default="",
        description=(
            "Ready-to-inject prompt fragment describing authoritative style rules "
            "(weight ≥ 0.80). Auto-regenerated after each correction."
        ),
    )

    # ── Profile health ────────────────────────────────────────────────────────
    total_corrections: int = Field(default=0, description="Total corrections processed")
    authoritative_rules_count: int = Field(
        default=0,
        description="Rules with weight ≥ 0.80 (high-confidence, injected into prompts)",
    )
    last_correction_at: str | None = Field(default=None)

    # ── Version tracking ─────────────────────────────────────────────────────
    profile_version: int = Field(
        default=1,
        description="Incremented each time rules change — used by generators to detect stale caches",
    )
