"""MarketInsight — TrendAnalyst output model.

A ``MarketInsight`` is a detected macro-level pattern across multiple signals,
rather than a single signal's classification. While the ``SignalEngine`` asks
"what happened to this company?", the ``TrendAnalyst`` asks "what is happening
across the market right now?"

These insights feed the ``StrategyGeneratorService`` to create context-aware
battlecards that reference sector momentum and competitive dynamics.

Examples of insights:
- "B2B SaaS funding events up 40% this week — sector is hot, urgency high."
- "Healthcare sector showing unusual hiring surge — 7 signals in 3 days."
- "Post-series-B outreach playbook converted 3 more deals this week."

Insight lifecycle
-----------------
Insights are generated by the TrendAnalyst on a rolling basis. Stale insights
(older than ``ttl_hours``) are soft-expired and not injected into new contexts.
This ensures generators always reason from fresh market data.
"""

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import JSON, Column
from sqlmodel import Field

from app.models.base import InsightType, TimestampMixin, new_uuid


class MarketInsight(TimestampMixin, table=True):
    """A detected macro market pattern."""

    __tablename__ = "market_insights"

    id: uuid.UUID = Field(default_factory=new_uuid, primary_key=True, index=True)

    # Tenant boundary. Nullable for backward compatibility — see
    # app.models.organization's docstring.
    organization_id: uuid.UUID | None = Field(
        default=None, foreign_key="organizations.id", index=True
    )

    # ── Classification ─────────────────────────────────────────────────────
    insight_type: InsightType = Field(index=True, nullable=False)

    # Scope: which signal_type and/or industry this insight applies to.
    signal_type: str | None = Field(default=None, index=True)
    industry: str | None = Field(default=None, index=True)

    # ── Content ─────────────────────────────────────────────────────────────
    title: str = Field(nullable=False)
    # Plain-text description for injecting into LLM prompts and dashboard.
    description: str = Field(nullable=False)
    # Recommendation for generators: what to do differently given this insight.
    tactical_implication: str | None = Field(default=None)

    # ── Evidence ────────────────────────────────────────────────────────────
    # How confident is the analyst that this pattern is real (0-1)?
    confidence: float = Field(default=0.5)
    # Number of signals that contributed to this insight.
    evidence_count: int = Field(default=0)
    # Raw aggregation data for auditability.
    evidence: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))

    # ── Freshness ────────────────────────────────────────────────────────────
    # Hours after which this insight should no longer be injected into contexts.
    ttl_hours: int = Field(default=168)  # 7 days default
    expires_at: datetime | None = Field(default=None, index=True)
    is_active: bool = Field(default=True, index=True)

    @property
    def is_fresh(self) -> bool:
        if self.expires_at is None:
            return self.is_active
        now = datetime.now(UTC)
        exp = self.expires_at
        if exp.tzinfo is None:
            exp = exp.replace(tzinfo=UTC)
        return self.is_active and now < exp

    def to_prompt_text(self) -> str:
        """Format for injection into LLM system prompts."""
        return (
            f"[Market Insight — {self.insight_type.value}] {self.description}"
            + (f" Tactical implication: {self.tactical_implication}" if self.tactical_implication else "")
        )
