"""Opportunity (Oportunidad) entity.

An Opportunity is the actionable core of BEE: it connects a **lead** + a
**signal** + a **strategy** (the recommended play to act on the signal). This is
where raw market intelligence becomes an executable sales motion.

The ``strategy`` field is intentionally a structured JSON document so the future
AI layer can populate rich, evolving playbooks (recommended messaging, channel,
timing, next best action) without further schema migrations.
"""

import uuid
from datetime import date, datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import JSON, Column
from sqlmodel import Field, Relationship

from app.models.base import OpportunityStatus, TimestampMixin, new_uuid

if TYPE_CHECKING:  # pragma: no cover
    from app.models.company import Company
    from app.models.lead import Lead
    from app.models.signal import Signal


class Opportunity(TimestampMixin, table=True):
    """A prioritized sales opportunity linking lead + signal + strategy."""

    __tablename__ = "opportunities"

    id: uuid.UUID = Field(default_factory=new_uuid, primary_key=True, index=True)

    # The three pillars of an opportunity. ``signal_id`` is the originating
    # trigger; ``lead_id``/``company_id`` are the target of the play.
    signal_id: uuid.UUID | None = Field(
        default=None, foreign_key="signals.id", index=True
    )
    lead_id: uuid.UUID | None = Field(default=None, foreign_key="leads.id", index=True)
    company_id: uuid.UUID | None = Field(
        default=None, foreign_key="companies.id", index=True
    )
    # Tenant boundary. Nullable for backward compatibility — see
    # app.models.organization's docstring.
    organization_id: uuid.UUID | None = Field(
        default=None, foreign_key="organizations.id", index=True
    )
    # The rep this opportunity is assigned to — the primary field
    # app.services.permissions filters on for manager/member visibility.
    assigned_to_user_id: uuid.UUID | None = Field(
        default=None, foreign_key="users.id", index=True
    )

    title: str = Field(nullable=False)
    status: OpportunityStatus = Field(default=OpportunityStatus.DETECTED, index=True)

    # Priority score (0-100) used to rank opportunities in the pipeline.
    score: float = Field(default=0.0, index=True)

    # The recommended play — enriched by StrategyGeneratorService.
    strategy: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))

    # Execution artifacts generated by ExecutiveAgent on demand:
    # email draft, meeting structure, next steps. Null until first generated.
    execution_artifacts: dict[str, Any] | None = Field(
        default=None, sa_column=Column(JSON)
    )

    # ----- Forecasting & qualification (revenue intelligence) ------------------
    # Estimated deal value — the input every weighted-forecast calculation
    # needs. Optional: many opportunities start without a number attached.
    amount: float | None = Field(default=None)
    # When the rep expects to close. Drives which forecast month/quarter a
    # deal lands in; also the basis for flagging a stale "at risk" deal.
    expected_close_date: date | None = Field(default=None, index=True)
    # MEDDIC qualification checklist — one bool per pillar (metric,
    # economic_buyer, decision_criteria, decision_process, identify_pain,
    # champion). A JSON map (not fixed columns) so the set of criteria can
    # evolve — e.g. swapping in BANT — without another migration. Missing
    # keys read as "not yet confirmed", never as "disqualified".
    qualification: dict[str, bool] = Field(default_factory=dict, sa_column=Column(JSON))

    # ----- Outcome detail (Win/Loss Analysis) -----------------------------------
    # Set once, by FeedbackLoopService.record_outcome, the moment status
    # transitions to WON/LOST — never edited afterward (outcome recording is
    # idempotent, see FeedbackLoopService). Kept on the opportunity itself
    # (not only on StrategyOutcome) so the frontend can build Win/Loss
    # breakdowns straight from the same bulk opportunity list it already
    # fetches for Pronóstico/Tendencias, with no extra endpoint.
    loss_reason: str | None = Field(default=None, max_length=64, index=True)
    competitor: str | None = Field(default=None, max_length=200)
    closed_at: datetime | None = Field(default=None)

    # ----- Relationships -------------------------------------------------------
    signal: "Signal" = Relationship(back_populates="opportunities")
    lead: "Lead" = Relationship(back_populates="opportunities")
    company: "Company" = Relationship(back_populates="opportunities")
