"""DynamicSequence models — state-machine based outreach sequences.

Unlike linear drip campaigns, DynamicSequences are DAGs: each step has
conditional transitions that decide the next step based on engagement events
(email_opened, link_clicked, replied, etc.).

This enables reactive sequences: the system adapts to what the lead does,
not just to a fixed timeline.

Example sequence flow
---------------------
::

    Step 1: send_email(type=intro_email)
        ├─ if email_opened AND NOT link_clicked  → Step 2a: send_linkedin_connect
        ├─ if link_clicked                        → Step 2b: book_meeting
        └─ if not_opened(3d)                      → Step 1b: send_followup_email

    Step 2a: send_linkedin_connect
        ├─ if accepted                            → Step 3: send_case_study
        └─ if not_accepted(7d)                    → COMPLETED (give up gracefully)

Security contract
-----------------
Every step that results in an outbound action creates a ``PendingAction``
in the AgentOrchestrator. The sequence engine NEVER sends anything directly.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import JSON, Column
from sqlmodel import Field

from app.models.base import TimestampMixin, new_uuid


class SequenceStatus(str):
    DRAFT = "draft"         # Not yet activated
    ACTIVE = "active"       # At least one execution running
    PAUSED = "paused"       # Temporarily halted
    ARCHIVED = "archived"   # No longer in use


class ExecutionStatus(str):
    RUNNING = "running"
    WAITING = "waiting"     # Waiting for an event/trigger condition
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class DynamicSequence(TimestampMixin, table=True):
    """A reusable, named sequence definition.

    Contains the full step graph as JSON. This design avoids a complex
    relational step-table and keeps the entire sequence definition
    queryable and serializable as a single record.
    """

    __tablename__ = "dynamic_sequences"

    id: uuid.UUID = Field(default_factory=new_uuid, primary_key=True, index=True)
    name: str = Field(index=True, unique=True, nullable=False)
    description: str | None = Field(default=None)

    # Target segment
    signal_type: str | None = Field(default=None, index=True)
    industry: str | None = Field(default=None)

    # ── Step graph (JSON) ─────────────────────────────────────────────────────
    # Schema: list of StepDefinition dicts.
    # Each StepDefinition: { id, action, artifact_type, transitions: [{condition, next_step_id}] }
    steps: list[dict[str, Any]] = Field(default_factory=list, sa_column=Column(JSON))

    # ── Entry point ───────────────────────────────────────────────────────────
    entry_step_id: str = Field(default="s1", description="ID of the first step to execute.")

    # ── Sequence-level timing ─────────────────────────────────────────────────
    max_days: int = Field(default=30, description="Auto-complete the sequence after this many days.")

    status: str = Field(default=SequenceStatus.DRAFT, index=True)
    version: int = Field(default=1)

    @property
    def step_map(self) -> dict[str, dict[str, Any]]:
        """Return steps indexed by step ID for fast lookup."""
        return {s["id"]: s for s in self.steps}


class SequenceExecution(TimestampMixin, table=True):
    """One running instance of a DynamicSequence for a specific lead/opportunity.

    Tracks the current position in the sequence graph, the full event history,
    and links to each PendingAction generated by the sequence steps.
    """

    __tablename__ = "sequence_executions"

    id: uuid.UUID = Field(default_factory=new_uuid, primary_key=True, index=True)
    sequence_id: uuid.UUID = Field(foreign_key="dynamic_sequences.id", index=True)
    opportunity_id: uuid.UUID | None = Field(default=None, index=True)
    lead_id: uuid.UUID | None = Field(default=None, index=True)

    # ── State machine ─────────────────────────────────────────────────────────
    current_step_id: str = Field(nullable=False)
    status: str = Field(default=ExecutionStatus.RUNNING, index=True)

    # ── Event journal ─────────────────────────────────────────────────────────
    # List of { event: str, timestamp: ISO, metadata: dict }
    events: list[dict[str, Any]] = Field(default_factory=list, sa_column=Column(JSON))

    # ── Pending actions spawned ───────────────────────────────────────────────
    # List of pending_action_ids created by this sequence so far.
    pending_action_ids: list[str] = Field(default_factory=list, sa_column=Column(JSON))

    # ── Timing ───────────────────────────────────────────────────────────────
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    last_advanced_at: datetime | None = Field(default=None)
    completed_at: datetime | None = Field(default=None)

    def record_event(self, event: str, metadata: dict[str, Any] | None = None) -> None:
        """Append an engagement event to the journal."""
        self.events = [
            *self.events,
            {"event": event, "timestamp": datetime.now(UTC).isoformat(), "metadata": metadata or {}},
        ]
        self.last_advanced_at = datetime.now(UTC)

    def all_event_names(self) -> list[str]:
        """Return all recorded event names (for transition matching)."""
        return [e["event"] for e in self.events]
