"use client";

import { useState } from "react";
import {
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clock,
  Copy,
  Mail,
  ListChecks,
  AlertTriangle,
  Zap,
} from "lucide-react";
import type { ArtifactBundle, ActionItem } from "@/lib/types";

interface ExecutionArtifactsProps {
  bundle: ArtifactBundle;
  opportunityId: string;
}

const priorityColors: Record<ActionItem["priority"], string> = {
  high: "bg-red-50 border-red-200 text-red-700",
  medium: "bg-amber-50 border-amber-200 text-amber-700",
  low: "bg-slate-50 border-slate-200 text-slate-600",
};

const ownerLabels: Record<ActionItem["owner"], string> = {
  rep: "You",
  lead: "Lead",
  both: "Both",
};

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1 text-xs text-slate-400 hover:text-slate-700 transition-colors"
    >
      {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

function CollapsibleSection({
  title,
  icon: Icon,
  children,
  defaultOpen = false,
  badge,
}: {
  title: string;
  icon: React.ElementType;
  children: React.ReactNode;
  defaultOpen?: boolean;
  badge?: string;
}) {
  const [open, setOpen] = useState(defaultOpen);

  return (
    <div className="border border-slate-200 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-4 py-3 bg-slate-50 hover:bg-slate-100 transition-colors"
      >
        <div className="flex items-center gap-2">
          <Icon className="w-4 h-4 text-slate-500" />
          <span className="text-sm font-semibold text-slate-800">{title}</span>
          {badge && (
            <span className="text-xs bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full font-medium">
              {badge}
            </span>
          )}
        </div>
        {open ? (
          <ChevronUp className="w-4 h-4 text-slate-400" />
        ) : (
          <ChevronDown className="w-4 h-4 text-slate-400" />
        )}
      </button>
      {open && <div className="p-4">{children}</div>}
    </div>
  );
}

export function ExecutionArtifacts({ bundle }: ExecutionArtifactsProps) {
  const { email_draft, meeting_structure, next_steps } = bundle;

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        <Zap className="w-4 h-4 text-indigo-500" />
        <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide">
          Execution Artifacts
        </h3>
        <span className="text-xs text-slate-400">
          Generated by {bundle.generator}
        </span>
      </div>

      {/* Email Draft */}
      <CollapsibleSection
        title="Email Draft"
        icon={Mail}
        defaultOpen={true}
        badge="One-Click Send"
      >
        <div className="space-y-3">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs text-slate-500 mb-1">Subject</p>
              <p className="text-sm font-medium text-slate-800">{email_draft.subject}</p>
            </div>
            <CopyButton text={email_draft.subject} />
          </div>

          <div>
            <div className="flex items-center justify-between mb-1">
              <p className="text-xs text-slate-500">Body</p>
              <CopyButton
                text={
                  email_draft.body +
                  (email_draft.ps_line ? `\n\n${email_draft.ps_line}` : "")
                }
              />
            </div>
            <pre className="text-sm text-slate-700 bg-slate-50 rounded-lg p-3 whitespace-pre-wrap font-sans leading-relaxed border border-slate-100">
              {email_draft.body}
            </pre>
            {email_draft.ps_line && (
              <p className="mt-2 text-sm text-slate-600 italic pl-3 border-l-2 border-indigo-200">
                {email_draft.ps_line}
              </p>
            )}
          </div>

          {email_draft.recommended_send_time && (
            <div className="flex items-center gap-1.5 text-xs text-slate-500">
              <Clock className="w-3.5 h-3.5" />
              Best time to send: {email_draft.recommended_send_time}
            </div>
          )}
        </div>
      </CollapsibleSection>

      {/* Meeting Structure */}
      <CollapsibleSection
        title="Meeting Agenda"
        icon={Calendar}
        badge={`${meeting_structure.total_duration_minutes} min`}
      >
        <div className="space-y-4">
          <div>
            <p className="text-xs text-slate-500 mb-1">Objective</p>
            <p className="text-sm text-slate-700">{meeting_structure.objective}</p>
          </div>

          <div>
            <p className="text-xs text-slate-500 mb-2">Agenda</p>
            <div className="space-y-2">
              {meeting_structure.agenda_items.map((item, i) => (
                <div key={i} className="flex items-start gap-3 text-sm">
                  <span className="min-w-[40px] text-xs text-slate-400 pt-0.5">
                    {item.duration_minutes}m
                  </span>
                  <div>
                    <p className="font-medium text-slate-800">{item.title}</p>
                    {item.notes && (
                      <p className="text-xs text-slate-500 mt-0.5">{item.notes}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {meeting_structure.pre_meeting_prep.length > 0 && (
            <div>
              <p className="text-xs text-slate-500 mb-2">Pre-meeting prep</p>
              <ul className="space-y-1">
                {meeting_structure.pre_meeting_prep.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-600">
                    <CheckCircle2 className="w-3 h-3 text-emerald-400 mt-0.5 flex-shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="text-xs text-slate-500 bg-emerald-50 rounded-lg p-2.5 border border-emerald-100">
            <span className="font-medium text-emerald-700">Success criteria: </span>
            {meeting_structure.success_criteria}
          </div>
        </div>
      </CollapsibleSection>

      {/* Next Steps */}
      <CollapsibleSection
        title="Action Plan"
        icon={ListChecks}
        badge={next_steps.horizon}
      >
        <div className="space-y-3">
          <div className="space-y-2">
            {next_steps.actions.map((action, i) => (
              <div
                key={i}
                className={`flex items-start gap-3 text-xs rounded-lg border px-3 py-2 ${priorityColors[action.priority]}`}
              >
                <div className="flex-1">
                  <p className="font-medium">{action.action}</p>
                  <div className="flex items-center gap-2 mt-0.5 opacity-75">
                    <span>{ownerLabels[action.owner]}</span>
                    <span>·</span>
                    <Clock className="w-3 h-3" />
                    <span>{action.timing}</span>
                  </div>
                </div>
                <span className="capitalize font-medium shrink-0">{action.priority}</span>
              </div>
            ))}
          </div>

          {next_steps.key_risk && (
            <div className="flex items-start gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg p-2.5">
              <AlertTriangle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
              <div>
                <span className="font-medium">Key risk: </span>
                {next_steps.key_risk}
              </div>
            </div>
          )}

          {next_steps.success_milestone && (
            <div className="flex items-start gap-2 text-xs text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-lg p-2.5">
              <CheckCircle2 className="w-3.5 h-3.5 mt-0.5 shrink-0" />
              <div>
                <span className="font-medium">Success milestone: </span>
                {next_steps.success_milestone}
              </div>
            </div>
          )}
        </div>
      </CollapsibleSection>
    </div>
  );
}
