"""ContentStyleMiddleware — the DISC tone adaptation filter.

Every piece of content generated by BEE (emails, LinkedIn messages, meeting
agendas, next steps) passes through this middleware before being delivered
to the CEO for review.

The middleware DOES NOT change the facts or strategic content — it adapts
the tone, emphasis, structure, and phrasing to match the lead's DISC style.

Architecture: Middleware chain
------------------------------
::

    raw_content (from ExecutiveAgent / SmartEngagementEngine)
        │
        ▼
    ContentStyleMiddleware.adapt(content, profile, artifact_type)
        │
        ├── D-style: strip pleasantries, lead with ROI/numbers, shorten
        ├── I-style: add human opener, social proof anchor, energetic CTA
        ├── S-style: add warmth, process context, remove urgency language
        └── C-style: add data framing, logic-first, precision language
        │
        ▼
    AdaptedContent { adapted, adaptations_applied, confidence }
        │
        ▼
    PendingAction.preview = adapted content

The middleware is applied in ``ExecutiveAgent._finalize_artifacts()`` and
in ``SmartEngagementEngine._generate_response()`` when a psychographic
profile is available for the lead.

LLM upgrade path
----------------
Replace ``_apply_d_style()``, ``_apply_i_style()``, etc. with a single
LLM call that takes (content, style_instructions) and returns adapted
content. The middleware interface and all call sites remain identical.
"""

from __future__ import annotations

import re

from app.models.psychographic import LeadPsychographic
from app.schemas.psychographic import AdaptedContent
from app.services.psychographic.classifier import STYLE_PREFERENCES

# ── Pleasantry patterns to remove for D-style ─────────────────────────────────
_PLEASANTRY_PATTERNS = [
    r"hope you(?:'re| are) (?:doing |having )?(?:well|great|good)(?:[.!,])?",
    r"hope this (?:email |message )?finds you well[.!]?",
    r"just wanted to (?:reach out|check in|follow up|touch base)[.!,]?",
    r"as per (?:our|my) (?:previous|last) (?:email|message|conversation)[,.]?",
    r"i (?:hope|trust) (?:this|you)[^.]*[.!]",
]

# ── Urgency patterns to soften for S-style ────────────────────────────────────
_URGENCY_PATTERNS = [
    (r"\burgently\b", "when you have a moment"),
    (r"\bASAP\b|\bas soon as possible\b", "at your convenience"),
    (r"\bimmediately\b", "in the near future"),
    (r"\bdisrupt\b", "transform"),
    (r"\baggressive(?:ly)?\b", "proactive"),
]

# ── Casual softeners to replace with precision for C-style ────────────────────
_VAGUE_PATTERNS = [
    (r"\btrust me\b", "based on our data"),
    (r"\beveryone knows\b", "research indicates"),
    (r"\bbest in class\b", "top-quartile performing"),
    (r"\bindustry.leading\b", "top-performing in the sector"),
    (r"\bamazing\b", "effective"),
    (r"\bgreat\b", "strong"),
]


class ContentStyleMiddleware:
    """Adapts generated content to match a lead's DISC communication style.

    Usage::

        middleware = ContentStyleMiddleware()
        result = middleware.adapt(content, profile, artifact_type="email_draft")
        final_text = result.adapted

    Thread-safe: stateless, no mutable shared state.
    """

    def adapt(
        self,
        content: str,
        profile: LeadPsychographic,
        artifact_type: str = "email_draft",
    ) -> AdaptedContent:
        """Apply DISC style adaptation to the given content.

        Args:
            content:       The raw generated content (email body, message, etc.)
            profile:       The lead's DISC psychographic profile.
            artifact_type: Type of content (affects structural rules).

        Returns:
            An :class:`AdaptedContent` with the adapted text and a log of
            changes applied.
        """
        style = profile.dominant_style
        adaptations: list[str] = []

        adapted = content
        prefs = STYLE_PREFERENCES.get(style, {})

        if style == "D":
            adapted, applied = self._apply_d_style(adapted, artifact_type)
            adaptations.extend(applied)
        elif style == "I":
            adapted, applied = self._apply_i_style(adapted, artifact_type)
            adaptations.extend(applied)
        elif style == "S":
            adapted, applied = self._apply_s_style(adapted, artifact_type)
            adaptations.extend(applied)
        elif style == "C":
            adapted, applied = self._apply_c_style(adapted, artifact_type)
            adaptations.extend(applied)
        else:
            adaptations.append("no_adaptation: unknown style")

        # Always append a style note for the CEO in the approval UI
        style_note = f"\n\n[DISC style applied: {profile.style_label} — {prefs.get('tone', 'professional')} tone]"
        adapted = adapted + style_note

        return AdaptedContent(
            original=content,
            adapted=adapted,
            disc_style=style,
            adaptations_applied=adaptations,
            confidence=profile.confidence,
            artifact_type=artifact_type,
        )

    # ── Style-specific adapters ───────────────────────────────────────────────

    def _apply_d_style(self, content: str, artifact_type: str) -> tuple[str, list[str]]:  # noqa: ARG002
        """D-type: Direct, brief, ROI-first. Strip pleasantries and fluff."""
        applied = []
        result = content

        # Remove pleasantries
        for pattern in _PLEASANTRY_PATTERNS:
            new = re.sub(pattern, "", result, flags=re.IGNORECASE).strip()
            if new != result:
                applied.append("removed_pleasantry")
                result = new

        # Replace "I wanted to" with direct action
        new = re.sub(r"\bI (?:wanted|would like) to\b", "I'm", result, flags=re.IGNORECASE)
        if new != result:
            applied.append("direct_opener")
            result = new

        if not applied:
            applied.append("d_style_minor_adjustments")

        return result.strip(), applied

    def _apply_i_style(self, content: str, artifact_type: str) -> tuple[str, list[str]]:
        """I-type: Add human element, social proof, energetic CTA."""
        applied = []
        result = content

        # Add social proof signal if content doesn't already have one
        if (
            not any(kw in content.lower() for kw in ["other companies", "clients", "customers", "teams"])
            and artifact_type in ("email_draft", "linkedin_message")
        ):
            result += "\n\nP.S. Companies like yours are seeing great results with this approach."
            applied.append("added_social_proof")

        # Soften corporate language
        new = re.sub(r"\bleverage\b", "use", result, flags=re.IGNORECASE)
        if new != result:
            applied.append("softened_corporate_jargon")
            result = new

        if not applied:
            applied.append("i_style_review_tone")

        return result, applied

    def _apply_s_style(self, content: str, artifact_type: str) -> tuple[str, list[str]]:  # noqa: ARG002
        """S-type: Warm, reassuring, low-pressure, process-focused."""
        applied = []
        result = content

        # Soften urgency language
        for pattern, replacement in _URGENCY_PATTERNS:
            new = re.sub(pattern, replacement, result, flags=re.IGNORECASE)
            if new != result:
                applied.append(f"softened_urgency: {pattern}")
                result = new

        # Add reassurance if not present
        if (
            "no pressure" not in result.lower()
            and "at your pace" not in result.lower()
            and "?" in result
        ):
            result = result.replace(
                "?",
                "? (No pressure — happy to chat whenever works for you.)",
                1,
            )
            applied.append("added_reassurance")

        if not applied:
            applied.append("s_style_minor_warmth")

        return result, applied

    def _apply_c_style(self, content: str, artifact_type: str) -> tuple[str, list[str]]:  # noqa: ARG002
        """C-type: Data-first, logical, replace vague claims with precision."""
        applied = []
        result = content

        # Replace vague claims
        for pattern, replacement in _VAGUE_PATTERNS:
            new = re.sub(pattern, replacement, result, flags=re.IGNORECASE)
            if new != result:
                applied.append(f"precision_replacement: {pattern}")
                result = new

        # Add data framing if not present
        if not any(kw in content.lower() for kw in ["%", "data", "metrics", "rate", "roi", "benchmark"]):
            result += "\n\nI can share the specific metrics and methodology behind this if useful."
            applied.append("added_data_offer")

        if not applied:
            applied.append("c_style_precision_review")

        return result, applied
