"""PgVectorStore — persistent vector similarity search backed by pgvector.

This is BEE's production vector store: every WON opportunity strategy is encoded
as a dense semantic vector and stored permanently in PostgreSQL via the pgvector
extension. Unlike the MockVectorStore, data survives restarts, deployments, and
horizontal scaling.

Architecture
------------
Embeddings are generated by the configured embedding model (default:
``text-embedding-3-small`` from OpenAI, 1536 dimensions). The dense vector is
stored in a ``VECTOR(1536)`` column indexed by HNSW (Hierarchical Navigable
Small World), which provides:

* Sub-millisecond nearest-neighbour search at millions of vectors
* No training required (unlike IVFFlat) — works from document 0
* Cosine similarity scoring — consistent with the MockVectorStore interface

Embedding provider
------------------
When ``AI_PROVIDER=openai``, embeddings use OpenAI's API.
When ``AI_PROVIDER=none`` and ``VECTOR_STORE_BACKEND=pgvector`` is set, a
warning is logged and the store falls back to keyword-frequency embeddings
(same as MockVectorStore) stored as fixed-dimension float arrays in the pgvector
column. This allows pgvector persistence without requiring an OpenAI API key,
at the cost of lower semantic quality.

Connection management
---------------------
Uses a raw psycopg3 connection obtained from SQLAlchemy's connection pool.
This avoids duplicating connection management while keeping the vector store
decoupled from SQLModel sessions (so it can be called from background workers
and tests without an active HTTP request context).

Thread safety
-------------
All methods acquire a connection from the pool, perform the operation, and
release it immediately. The store itself is stateless and safe to share
across threads.
"""

from __future__ import annotations

import json
import math
import re
import time
from collections import defaultdict
from typing import Any

from app.core.config import get_settings
from app.core.logging import get_logger
from app.services.vector_store.interface import IVectorStore, ScoredDocument

logger = get_logger(__name__)

_settings = get_settings()


# ---------------------------------------------------------------------------
# Embedding helpers
# ---------------------------------------------------------------------------


def _openai_embed(texts: list[str]) -> list[list[float]]:
    """Batch-embed texts using OpenAI text-embedding-3-small.

    Batches up to 2048 texts per API call (OpenAI limit).
    Returns the embeddings in the same order as the input.
    """
    from openai import OpenAI

    client = OpenAI(api_key=_settings.AI_API_KEY, timeout=_settings.AI_TIMEOUT_SECONDS)
    response = client.embeddings.create(
        input=texts,
        model=_settings.EMBEDDING_MODEL,
        dimensions=_settings.EMBEDDING_DIMENSIONS,
    )
    return [item.embedding for item in response.data]


def _keyword_embed(text: str, dim: int = 256) -> list[float]:
    """Fallback keyword-frequency embedding when no AI key is configured.

    Uses a deterministic hash-based bucketing scheme to produce a fixed-dimension
    float vector. Lower semantic quality than dense embeddings, but enables
    pgvector persistence without external API dependencies.
    """
    tokens = re.findall(r"[a-záéíóúüñ\w]+", text.lower())
    counts: dict[int, float] = defaultdict(float)
    for t in tokens:
        bucket = hash(t) % dim
        counts[bucket] += 1.0
    vec = [counts.get(i, 0.0) for i in range(dim)]
    # L2 normalize
    mag = math.sqrt(sum(x * x for x in vec)) or 1.0
    return [x / mag for x in vec]


def _cosine(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b, strict=True))
    mag_a = math.sqrt(sum(x * x for x in a))
    mag_b = math.sqrt(sum(x * x for x in b))
    if mag_a == 0 or mag_b == 0:
        return 0.0
    return dot / (mag_a * mag_b)


# ---------------------------------------------------------------------------
# PgVectorStore
# ---------------------------------------------------------------------------


class PgVectorStore(IVectorStore):
    """Production vector store using PostgreSQL + pgvector.

    Provides the same ``IVectorStore`` interface as ``MockVectorStore`` so all
    services that depend on the interface work identically in both environments.

    Configuration (via env vars):
    * ``VECTOR_STORE_BACKEND=pgvector``  — activates this store
    * ``AI_PROVIDER=openai``             — use OpenAI embeddings (recommended)
    * ``AI_API_KEY=sk-...``              — OpenAI key
    * ``EMBEDDING_MODEL=text-embedding-3-small`` — embedding model
    * ``EMBEDDING_DIMENSIONS=1536``      — must match model output

    Without a valid ``AI_API_KEY``, falls back to keyword embeddings (lower
    quality but fully functional for persistence and basic similarity).
    """

    _TABLE = "vector_embeddings"

    def __init__(self, database_url: str | None = None) -> None:
        self._db_url = database_url or _settings.sqlalchemy_database_uri
        self._use_openai = (
            _settings.AI_PROVIDER == "openai" and bool(_settings.AI_API_KEY)
        )
        self._dim = _settings.EMBEDDING_DIMENSIONS if self._use_openai else 256

        if not self._use_openai:
            logger.warning(
                "PgVectorStore: AI_PROVIDER is not 'openai' or AI_API_KEY is missing. "
                "Using keyword-frequency embeddings (dim=256). "
                "Set AI_PROVIDER=openai and AI_API_KEY for production-quality semantic search."
            )

        logger.info(
            "PgVectorStore initialised — backend=pgvector dim=%d openai_embeddings=%s",
            self._dim,
            self._use_openai,
        )

    # ── IVectorStore API ──────────────────────────────────────────────────────

    def embed(self, text: str) -> list[float]:
        """Generate an embedding vector for the given text."""
        if self._use_openai:
            return _openai_embed([text])[0]
        return _keyword_embed(text, self._dim)

    def upsert(
        self,
        doc_id: str,
        content: str,
        metadata: dict[str, Any] | None = None,
        source: str = "sales_dna",
    ) -> None:
        """Embed and persistently store a document.

        Uses INSERT ... ON CONFLICT (doc_id) DO UPDATE so re-indexing an
        existing document is safe and idempotent.
        """
        t0 = time.monotonic()
        vector = self.embed(content)
        embed_ms = int((time.monotonic() - t0) * 1000)

        # Format as pgvector literal: [f1,f2,...,fn]
        vec_str = "[" + ",".join(f"{v:.8f}" for v in vector) + "]"
        meta_json = json.dumps(metadata or {})

        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"""
                    INSERT INTO {self._TABLE}
                        (doc_id, content, embedding, metadata_json, source, updated_at)
                    VALUES (%s, %s, %s::vector, %s, %s, NOW())
                    ON CONFLICT (doc_id) DO UPDATE SET
                        content       = EXCLUDED.content,
                        embedding     = EXCLUDED.embedding,
                        metadata_json = EXCLUDED.metadata_json,
                        source        = EXCLUDED.source,
                        updated_at    = NOW()
                    """,
                    (doc_id, content, vec_str, meta_json, source),
                )
            conn.commit()

        logger.debug(
            "PgVectorStore.upsert: doc_id=%s source=%s embed_ms=%d",
            doc_id, source, embed_ms,
        )

    def query(
        self,
        text: str,
        top_k: int = 5,
        filter_metadata: dict[str, Any] | None = None,  # noqa: ARG002
        source: str | None = None,
    ) -> list[ScoredDocument]:
        """Find semantically similar documents using HNSW cosine search.

        Args:
            text:            Query text to embed and search.
            top_k:           Maximum results to return.
            filter_metadata: Not supported for pgvector (metadata filtering
                             requires JSONB; use ``source`` for coarse filtering).
            source:          Restrict to documents from this source category
                             (e.g. ``"sales_dna"``, ``"brand"``).

        Returns:
            List of ``ScoredDocument`` sorted by descending cosine similarity.
        """
        query_vec = self.embed(text)
        vec_str = "[" + ",".join(f"{v:.8f}" for v in query_vec) + "]"

        source_filter = f"AND source = '{source}'" if source else ""

        with self._connect() as conn, conn.cursor() as cur:
            cur.execute(
                f"""
                    SELECT doc_id, content, metadata_json,
                           1 - (embedding <=> %s::vector) AS cosine_similarity
                    FROM {self._TABLE}
                    WHERE embedding IS NOT NULL {source_filter}
                    ORDER BY embedding <=> %s::vector
                    LIMIT %s
                    """,
                (vec_str, vec_str, top_k),
            )
            rows = cur.fetchall()

        results = []
        for doc_id, content, meta_raw, score in rows:
            try:
                metadata = json.loads(meta_raw) if meta_raw else {}
            except (json.JSONDecodeError, TypeError):
                metadata = {}

            results.append(
                ScoredDocument(
                    id=doc_id,
                    content=content,
                    score=round(float(score), 4),
                    metadata=metadata,
                )
            )

        return results

    def delete(self, doc_id: str) -> None:
        """Remove a document from the store."""
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"DELETE FROM {self._TABLE} WHERE doc_id = %s", (doc_id,)
                )
            conn.commit()

    def count(self) -> int:
        """Return the total number of documents in the store."""
        with self._connect() as conn, conn.cursor() as cur:
            cur.execute(f"SELECT COUNT(*) FROM {self._TABLE}")
            row = cur.fetchone()
            return int(row[0]) if row else 0

    def count_by_source(self, source: str) -> int:
        """Return document count filtered by source (e.g. 'sales_dna')."""
        with self._connect() as conn, conn.cursor() as cur:
            cur.execute(
                f"SELECT COUNT(*) FROM {self._TABLE} WHERE source = %s",
                (source,),
            )
            row = cur.fetchone()
            return int(row[0]) if row else 0

    # ── Connection management ─────────────────────────────────────────────────

    def _connect(self):
        """Return a psycopg3 connection from the configured DATABASE_URL.

        Uses the ``postgresql+psycopg://`` URL format already computed by
        :class:`~app.core.config.Settings`. The ``pgvector`` psycopg3 adapter
        is registered so the vector type is handled transparently.
        """
        import psycopg

        # Normalise the URL for psycopg3 (strip the SQLAlchemy driver prefix)
        url = self._db_url.replace("postgresql+psycopg://", "postgresql://")
        conn = psycopg.connect(url)
        return conn
