/**
 * Master domain types — canonical contract shared with the BEE API.
 *
 * Mirrors `apps/api/app/schemas/signal.py` and `strategy.py`.
 * Import from `@/types` (or `@/types/domain`) — never duplicate shapes elsewhere.
 */

// ── Enums (match Python StrEnum values) ─────────────────────────────────────

export type SignalType =
  | "funding_round"
  | "hiring"
  | "tech_adoption"
  | "leadership_change"
  | "product_launch"
  | "engagement"
  | "news_mention"
  | "expansion"
  | "other";

export type SignalSource =
  | "webhook"
  | "manual"
  | "scraper"
  | "integration"
  | "dark_funnel";

export type OpportunityStatus =
  | "detected"
  | "ready_to_action"
  | "prioritized"
  | "in_progress"
  | "won"
  | "lost"
  | "dismissed";

/** Terminal statuses — an opportunity in any of these never moves again.
 *  Single shared source: this used to be copy-pasted as a local constant in
 *  forecast.ts, lead-board.ts, record-outcome-panel.tsx, and
 *  relationship-map.ts — four places that had to be kept in lockstep by
 *  hand, with no guardrail if one drifted. */
export const CLOSED_OPPORTUNITY_STATUSES: readonly OpportunityStatus[] = [
  "won",
  "lost",
  "dismissed",
];

export type TimingUrgency = "immediate" | "this_week" | "this_month" | "watch";

// ── Inbound webhook refs (SignalWebhookIn) ───────────────────────────────────

export interface CompanyRef {
  name?: string | null;
  domain?: string | null;
  industry?: string | null;
  country?: string | null;
}

export interface LeadRef {
  full_name?: string | null;
  email?: string | null;
  title?: string | null;
  seniority?: string | null;
  linkedin_url?: string | null;
}

// ── SignalOut ─────────────────────────────────────────────────────────────────

export interface Signal {
  id: string;
  signal_type: SignalType;
  source: SignalSource | string;
  title: string;
  description: string | null;
  score: number;
  confidence: number;
  detected_at: string;
  company_id: string | null;
  lead_id: string | null;
  analysis: Record<string, unknown> & {
    tags?: string[];
    analyzers?: string[];
    primary_analyzer?: string;
  };
}

// ── StrategySchema (Opportunity.strategy JSON column) ─────────────────────────

export interface TimingWindow {
  urgency: TimingUrgency;
  reason: string;
  expires_at: string | null;
}

/** Fully-typed strategy contract — required for READY_TO_ACTION battlecards. */
export interface StrategySchema {
  pain_point: string;
  closing_argument: string;
  timing_window: TimingWindow;
  playbook: string;
  next_best_action: string;
  channel: string;
  rationale: string | null;
  generator: string;
  generator_version: string;
  generated_at: string;
  confidence_score: number;
  manual_review_required: boolean;
  variant_id: string | null;
  variant_arm: string | null;
}

/** Partial strategy while opportunity is still being enriched. */
export type StrategyPartial = Partial<StrategySchema> & Record<string, unknown>;

// ── OpportunityOut ────────────────────────────────────────────────────────────

export interface Opportunity {
  id: string;
  title: string;
  status: OpportunityStatus;
  score: number;
  strategy: StrategyPartial;
  signal_id: string | null;
  lead_id: string | null;
  company_id: string | null;
  assigned_to_user_id: string | null;
  // Forecasting & MEDDIC qualification — filled in by the rep, never
  // generated by BEE. See MeddicCriterion in lib/forecast.ts.
  amount: number | null;
  expected_close_date: string | null;
  qualification: Record<string, boolean>;
  created_at: string;
  updated_at: string;
  // Win/Loss Analysis — null until PATCH /{id}/outcome is called.
  loss_reason: LossReason | null;
  competitor: string | null;
  closed_at: string | null;
}

// ── SignalIngestResult ────────────────────────────────────────────────────────

export interface SignalIngestResult {
  signal: Signal;
  opportunity: Opportunity | null;
  analyzers_applied: string[];
  strategy_enriched: boolean;
  message: string;
}

// ── BattlecardOut ─────────────────────────────────────────────────────────────

export interface BattlecardCompany {
  name: string | null;
  domain: string | null;
  industry: string | null;
  country: string | null;
}

export interface BattlecardLead {
  full_name: string | null;
  title: string | null;
  email: string | null;
  seniority: string | null;
  linkedin_url: string | null;
}

export interface BattlecardSignal {
  id: string;
  signal_type: string;
  title: string;
  description: string | null;
  score: number;
  detected_at: string;
  tags: string[];
}

/** Alias — battlecard strategy is always fully typed StrategySchema. */
export type BattlecardStrategy = StrategySchema;

export interface Battlecard {
  opportunity_id: string;
  title: string;
  status: OpportunityStatus;
  score: number;
  ready_to_action: boolean;
  hot_lead: boolean;
  manual_review_required: boolean;
  company: BattlecardCompany;
  lead: BattlecardLead;
  signal: BattlecardSignal;
  strategy: BattlecardStrategy;
  created_at: string;
  updated_at: string;
}

// ── Execution artifacts (ExecutiveAgent) ──────────────────────────────────────

export interface EmailDraftArtifact {
  artifact_type: "email_draft";
  subject: string;
  body: string;
  ps_line: string | null;
  recommended_send_time: string | null;
  estimated_read_time_seconds: number;
}

export interface AgendaItem {
  duration_minutes: number;
  title: string;
  notes: string | null;
}

export interface MeetingStructureArtifact {
  artifact_type: "meeting_structure";
  meeting_title: string;
  total_duration_minutes: number;
  objective: string;
  agenda_items: AgendaItem[];
  pre_meeting_prep: string[];
  success_criteria: string;
}

export interface ActionItem {
  action: string;
  owner: "rep" | "lead" | "both";
  timing: string;
  priority: "high" | "medium" | "low";
}

export interface NextStepsArtifact {
  artifact_type: "next_steps";
  horizon: string;
  actions: ActionItem[];
  key_risk: string | null;
  success_milestone: string | null;
}

export interface ArtifactBundle {
  opportunity_id: string;
  generated_at: string;
  generator: string;
  email_draft: EmailDraftArtifact;
  meeting_structure: MeetingStructureArtifact;
  next_steps: NextStepsArtifact;
  context_snapshot: Record<string, unknown>;
}

// Fixed loss picklist — mirrors app.schemas.feedback.LossReason on the backend.
export type LossReason =
  | "price"
  | "budget"
  | "timing"
  | "competitor"
  | "no_decision"
  | "lost_champion"
  | "product_fit"
  | "no_response"
  | "other";

export interface OutcomeIn {
  outcome: "won" | "lost";
  loss_reason?: LossReason;
  competitor?: string;
  notes?: string;
}

export interface OutcomeOut {
  opportunity_id: string;
  outcome: string;
  loss_reason: string | null;
  competitor: string | null;
  closed_at: string;
  message: string;
}

// ── OpportunityTask ─────────────────────────────────────────────────────────

export interface OpportunityTask {
  id: string;
  opportunity_id: string;
  assigned_to_user_id: string | null;
  title: string;
  due_at: string | null;
  completed_at: string | null;
  created_at: string;
}

export interface OpportunityTaskCreateIn {
  opportunity_id: string;
  title: string;
  due_at?: string | null;
  assigned_to_user_id?: string | null;
}

export interface OpportunityTaskUpdateIn {
  title?: string;
  due_at?: string | null;
  assigned_to_user_id?: string | null;
  completed?: boolean;
}

// ── LeadOut ───────────────────────────────────────────────────────────────────

// ── CompanyOut ────────────────────────────────────────────────────────────────

export interface Company {
  id: string;
  name: string;
  domain: string | null;
  industry: string | null;
  size: string | null;
  country: string | null;
  revenue_range: string | null;
  website: string | null;
  description: string | null;
  attributes: Record<string, unknown>;
  created_at: string;
}

export type LeadStatus = "new" | "qualified" | "engaged" | "converted" | "disqualified";

export interface Lead {
  id: string;
  company_id: string | null;
  organization_id: string | null;
  assigned_to_user_id: string | null;
  full_name: string;
  email: string | null;
  title: string | null;
  seniority: string | null;
  linkedin_url: string | null;
  phone: string | null;
  status: LeadStatus;
  score: number;
  attributes: Record<string, unknown>;
  created_at: string;
  // Populated by DataValidator on the backend (create + on-demand re-check).
  data_freshness_score: number;
  validation_flags: string[];
  last_validated_at: string | null;
  stale_risk: boolean;
}
