/**
 * Master domain types — canonical contract shared with the BEE API.
 *
 * Mirrors `apps/api/app/schemas/signal.py` and `strategy.py`.
 * Import from `@/types` (or `@/types/domain`) — never duplicate shapes elsewhere.
 */

// ── Enums (match Python StrEnum values) ─────────────────────────────────────

export type SignalType =
  | "funding_round"
  | "hiring"
  | "tech_adoption"
  | "leadership_change"
  | "product_launch"
  | "engagement"
  | "news_mention"
  | "expansion"
  | "franchise_expansion"
  | "merger_acquisition"
  | "public_tender"
  | "regulatory_change"
  | "funding_grant"
  | "other";

export type SignalSource =
  | "webhook"
  | "manual"
  | "scraper"
  | "integration"
  | "dark_funnel";

export type OpportunityStatus =
  | "detected"
  | "ready_to_action"
  | "prioritized"
  | "in_progress"
  | "won"
  | "lost"
  | "dismissed";

/** Terminal statuses — an opportunity in any of these never moves again.
 *  Single shared source: this used to be copy-pasted as a local constant in
 *  forecast.ts, lead-board.ts, record-outcome-panel.tsx, and
 *  relationship-map.ts — four places that had to be kept in lockstep by
 *  hand, with no guardrail if one drifted. */
export const CLOSED_OPPORTUNITY_STATUSES: readonly OpportunityStatus[] = [
  "won",
  "lost",
  "dismissed",
];

export type TimingUrgency = "immediate" | "this_week" | "this_month" | "watch";

// ── Inbound webhook refs (SignalWebhookIn) ───────────────────────────────────

export interface CompanyRef {
  name?: string | null;
  domain?: string | null;
  industry?: string | null;
  country?: string | null;
}

export interface LeadRef {
  full_name?: string | null;
  email?: string | null;
  title?: string | null;
  seniority?: string | null;
  linkedin_url?: string | null;
}

// ── SignalOut ─────────────────────────────────────────────────────────────────

export interface Signal {
  id: string;
  signal_type: SignalType;
  source: SignalSource | string;
  title: string;
  description: string | null;
  score: number;
  confidence: number;
  detected_at: string;
  company_id: string | null;
  lead_id: string | null;
  analysis: Record<string, unknown> & {
    tags?: string[];
    analyzers?: string[];
    primary_analyzer?: string;
  };
}

// ── StrategySchema (Opportunity.strategy JSON column) ─────────────────────────

export interface TimingWindow {
  urgency: TimingUrgency;
  reason: string;
  expires_at: string | null;
}

/** Fully-typed strategy contract — required for READY_TO_ACTION battlecards. */
export interface StrategySchema {
  pain_point: string;
  closing_argument: string;
  timing_window: TimingWindow;
  playbook: string;
  next_best_action: string;
  channel: string;
  rationale: string | null;
  generator: string;
  generator_version: string;
  generated_at: string;
  confidence_score: number;
  manual_review_required: boolean;
  variant_id: string | null;
  variant_arm: string | null;
}

/** Partial strategy while opportunity is still being enriched. */
export type StrategyPartial = Partial<StrategySchema> & Record<string, unknown>;

// ── OpportunityOut ────────────────────────────────────────────────────────────

/**
 * Revenue Continuity Radar classification — see
 * app.models.base.OPPORTUNITY_TYPES / RevenueContinuityService on the
 * backend. "expansion"/"renewal_risk" only ever appear on a signal about a
 * company that already has a WON opportunity; every net-new prospect is
 * "new_logo".
 */
export type OpportunityType = "new_logo" | "expansion" | "renewal_risk";

export interface Opportunity {
  id: string;
  title: string;
  status: OpportunityStatus;
  opportunity_type: OpportunityType;
  score: number;
  strategy: StrategyPartial;
  signal_id: string | null;
  lead_id: string | null;
  company_id: string | null;
  assigned_to_user_id: string | null;
  // Forecasting & MEDDIC qualification — filled in by the rep, never
  // generated by BEE. See MeddicCriterion in lib/forecast.ts.
  amount: number | null;
  expected_close_date: string | null;
  qualification: Record<string, boolean>;
  // Deal context captured at manual creation — see new-opportunity-form.tsx.
  source: string | null;
  next_meeting_at: string | null;
  meetings_held_count: number;
  photo_url: string | null;
  created_at: string;
  updated_at: string;
  // Win/Loss Analysis — null until PATCH /{id}/outcome is called.
  loss_reason: LossReason | null;
  competitor: string | null;
  closed_at: string | null;
}

// ── SignalIngestResult ────────────────────────────────────────────────────────

export interface SignalIngestResult {
  signal: Signal;
  opportunity: Opportunity | null;
  analyzers_applied: string[];
  strategy_enriched: boolean;
  message: string;
}

// ── BattlecardOut ─────────────────────────────────────────────────────────────

export interface BattlecardCompany {
  name: string | null;
  domain: string | null;
  industry: string | null;
  country: string | null;
}

export interface BattlecardLead {
  full_name: string | null;
  title: string | null;
  email: string | null;
  seniority: string | null;
  linkedin_url: string | null;
}

export interface BattlecardSignal {
  id: string;
  signal_type: string;
  title: string;
  description: string | null;
  score: number;
  detected_at: string;
  tags: string[];
}

/** Alias — battlecard strategy is always fully typed StrategySchema. */
export type BattlecardStrategy = StrategySchema;

export interface Battlecard {
  opportunity_id: string;
  title: string;
  status: OpportunityStatus;
  opportunity_type: OpportunityType;
  score: number;
  ready_to_action: boolean;
  hot_lead: boolean;
  manual_review_required: boolean;
  company: BattlecardCompany;
  lead: BattlecardLead;
  signal: BattlecardSignal;
  strategy: BattlecardStrategy;
  created_at: string;
  updated_at: string;
}

// ── Execution artifacts (ExecutiveAgent) ──────────────────────────────────────

export interface EmailDraftArtifact {
  artifact_type: "email_draft";
  subject: string;
  body: string;
  ps_line: string | null;
  recommended_send_time: string | null;
  estimated_read_time_seconds: number;
}

export interface AgendaItem {
  duration_minutes: number;
  title: string;
  notes: string | null;
}

export interface MeetingStructureArtifact {
  artifact_type: "meeting_structure";
  meeting_title: string;
  total_duration_minutes: number;
  objective: string;
  agenda_items: AgendaItem[];
  pre_meeting_prep: string[];
  success_criteria: string;
}

export interface ActionItem {
  action: string;
  owner: "rep" | "lead" | "both";
  timing: string;
  priority: "high" | "medium" | "low";
}

export interface NextStepsArtifact {
  artifact_type: "next_steps";
  horizon: string;
  actions: ActionItem[];
  key_risk: string | null;
  success_milestone: string | null;
}

export interface ArtifactBundle {
  opportunity_id: string;
  generated_at: string;
  generator: string;
  email_draft: EmailDraftArtifact;
  meeting_structure: MeetingStructureArtifact;
  next_steps: NextStepsArtifact;
  context_snapshot: Record<string, unknown>;
}

// Fixed loss picklist — mirrors app.schemas.feedback.LossReason on the backend.
export type LossReason =
  | "price"
  | "budget"
  | "timing"
  | "competitor"
  | "no_decision"
  | "lost_champion"
  | "product_fit"
  | "no_response"
  | "other";

export interface OutcomeIn {
  outcome: "won" | "lost";
  loss_reason?: LossReason;
  competitor?: string;
  notes?: string;
}

export interface OutcomeOut {
  opportunity_id: string;
  outcome: string;
  loss_reason: string | null;
  competitor: string | null;
  closed_at: string;
  message: string;
}

// ── OpportunityTask ─────────────────────────────────────────────────────────

export interface OpportunityTask {
  id: string;
  opportunity_id: string;
  assigned_to_user_id: string | null;
  title: string;
  due_at: string | null;
  completed_at: string | null;
  created_at: string;
}

export interface OpportunityTaskCreateIn {
  opportunity_id: string;
  title: string;
  due_at?: string | null;
  assigned_to_user_id?: string | null;
}

export interface OpportunityTaskUpdateIn {
  title?: string;
  due_at?: string | null;
  assigned_to_user_id?: string | null;
  completed?: boolean;
}

// ── LeadOut ───────────────────────────────────────────────────────────────────

// ── CompanyOut ────────────────────────────────────────────────────────────────

export interface Company {
  id: string;
  organization_id: string | null;
  owner_user_id: string | null;
  name: string;
  domain: string | null;
  industry: string | null;
  size: string | null;
  country: string | null;
  revenue_range: string | null;
  website: string | null;
  description: string | null;
  attributes: Record<string, unknown>;
  created_at: string;
}

export type AccountActivityEventType = "viewed" | "edited" | "assigned";

export interface AccountActivityEvent {
  id: string;
  company_id: string;
  user_id: string;
  user_full_name: string;
  user_avatar_url: string | null;
  event_type: AccountActivityEventType;
  created_at: string;
}

export type LeadStatus = "new" | "qualified" | "engaged" | "converted" | "disqualified";

export interface Lead {
  id: string;
  company_id: string | null;
  organization_id: string | null;
  assigned_to_user_id: string | null;
  full_name: string;
  email: string | null;
  title: string | null;
  seniority: string | null;
  linkedin_url: string | null;
  phone: string | null;
  status: LeadStatus;
  score: number;
  attributes: Record<string, unknown>;
  created_at: string;
  // Populated by DataValidator on the backend (create + on-demand re-check).
  data_freshness_score: number;
  validation_flags: string[];
  last_validated_at: string | null;
  stale_risk: boolean;

  estimated_value: number | null;
  source: string | null;
  next_meeting_at: string | null;
  meetings_held_count: number;
  photo_url: string | null;
}

/** Where a new lead can land in the pipeline at creation time — mirrors
 * LEAD_PIPELINE_STAGES on the backend (schemas/lead.py). Deliberately
 * excludes ready_to_action (an earned state, never picked by hand — see
 * that constant's own comment) and the closed statuses. */
export type LeadPipelineStage = "detected" | "prioritized" | "in_progress";

/** "Ligado al cerebro de BEE" — what kind of account a meeting is with,
 * derived server-side from the linked Opportunity/Lead (see
 * app.api.v1.endpoints.meetings._client_context). Never set by hand. */
export type MeetingClientContext = "active_client" | "hot_lead" | "prospect" | "new_contact";

/** Personal color tag — picked freely by whoever creates the meeting,
 * purely organizational (unlike MeetingClientContext). Token names, not
 * raw hex — resolve through the same --color-chart-1..6 custom properties
 * everything else already uses. Mirrors MeetingColor in schemas/meeting.py. */
export type MeetingColor = "chart-1" | "chart-2" | "chart-3" | "chart-4" | "chart-5" | "chart-6" | "green-1" | "green-2" | "green-3";

export interface Meeting {
  id: string;
  created_by_user_id: string;
  opportunity_id: string | null;
  lead_id: string | null;
  title: string;
  purpose: string | null;
  starts_at: string;
  duration_minutes: number;
  meeting_url: string | null;
  attendee_user_ids: string[];
  // {user_id: "accepted" | "declined"} — an attendee id with no entry here
  // is implicitly "pending" (hasn't responded yet). See POST
  // /meetings/{id}/respond on the backend.
  attendee_responses: Record<string, "accepted" | "declined">;
  color: MeetingColor | null;
  // Set once via POST /meetings/{id}/complete — a scheduled meeting alone
  // never sets this. See that endpoint's own docstring for why the
  // distinction matters (this is what feeds the meeting back into
  // meetings_held_count and an engagement signal, nothing else does).
  completed_at: string | null;
  created_at: string;
  company_name: string | null;
  contact_name: string | null;
  client_context: MeetingClientContext | null;
}
