"""Baseline schema for all SQLModel domain entities.

Revision ID: 000_baseline_domain_models
Revises: (base — first migration)
Create Date: 2026-08-22

Creates every table backing ``app.models`` — the 4 core entities (Company,
Lead, Signal, Opportunity) plus the ~20 extension models (psychographic,
dark_funnel, network, anomaly, audit_trail, brand_profile, sequence,
workflow_task, tactic_variant, engagement_event, correction, dead_letter,
market_insight, strategy_outcome, pending_action).

Why this migration exists
--------------------------
Before this revision, ``001_pgvector_sales_dna`` was the *only* migration in
this project, and it only creates the ``vector_embeddings`` table (a raw,
non-ORM table backing ``PgVectorStore``). None of the domain tables SQLModel
actually depends on had a migration — schema provisioning relied entirely on
``init_db()`` -> ``SQLModel.metadata.create_all()``, called unconditionally on
every app boot (see ``app/main.py``'s lifespan). That contradicts this
project's own documented policy ("production uses Alembic, ``init_db()`` is
for local dev only") and means ``alembic upgrade head`` alone, on a fresh
database, produced a schema with *only* ``vector_embeddings`` — every domain
table would be missing.

This migration is the missing baseline. It is deliberately the *root* of the
migration chain (``down_revision = None``) and ``001_pgvector_sales_dna`` now
depends on it — domain tables are provisioned first, the optional pgvector
add-on second — mirroring the natural order a fresh deployment needs them in.

Generated via ``alembic revision --autogenerate`` against an empty Postgres
16 database with the full ``app.models`` metadata loaded, then reviewed by
hand for correct FK-dependency ordering (companies -> leads -> signals ->
opportunities; voice_profiles -> brand_fragments; dynamic_sequences ->
sequence_executions) — confirmed by applying and reverting it end-to-end
against a real Postgres instance before landing.
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '000_baseline_domain_models'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_alerts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rolling_rate', sa.Float(), nullable=False),
    sa.Column('baseline_rate', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('baseline_sample_size', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('supporting_data', sa.JSON(), nullable=True),
    sa.Column('pending_action_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alerts_alert_type'), 'anomaly_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_anomaly_alerts_id'), 'anomaly_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_alerts_pending_action_id'), 'anomaly_alerts', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_anomaly_alerts_severity'), 'anomaly_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_anomaly_alerts_status'), 'anomaly_alerts', ['status'], unique=False)
    op.create_table('artifact_corrections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edited_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diff_ops', sa.JSON(), nullable=True),
    sa.Column('extracted_rules', sa.JSON(), nullable=True),
    sa.Column('change_ratio', sa.Float(), nullable=False),
    sa.Column('psychographic_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_corrections_artifact_type'), 'artifact_corrections', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifact_corrections_id'), 'artifact_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_artifact_corrections_lead_id'), 'artifact_corrections', ['lead_id'], unique=False)
    op.create_index(op.f('ix_artifact_corrections_opportunity_id'), 'artifact_corrections', ['opportunity_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('pending_action_id', sa.Uuid(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('market_data_used', sa.JSON(), nullable=True),
    sa.Column('strategy_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_snapshot', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('generator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_agent_type'), 'audit_entries', ['agent_type'], unique=False)
    op.create_index(op.f('ix_audit_entries_confidence_score'), 'audit_entries', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_audit_entries_decision_type'), 'audit_entries', ['decision_type'], unique=False)
    op.create_index(op.f('ix_audit_entries_id'), 'audit_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entries_lead_id'), 'audit_entries', ['lead_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_manual_review_required'), 'audit_entries', ['manual_review_required'], unique=False)
    op.create_index(op.f('ix_audit_entries_opportunity_id'), 'audit_entries', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_pending_action_id'), 'audit_entries', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_session_id'), 'audit_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_signal_id'), 'audit_entries', ['signal_id'], unique=False)
    op.create_table('companies',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('dark_funnel_signals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_keywords', sa.JSON(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('contact_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dark_funnel_signals_company_domain'), 'dark_funnel_signals', ['company_domain'], unique=False)
    op.create_index(op.f('ix_dark_funnel_signals_id'), 'dark_funnel_signals', ['id'], unique=False)
    op.create_index(op.f('ix_dark_funnel_signals_lead_id'), 'dark_funnel_signals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_dark_funnel_signals_processed'), 'dark_funnel_signals', ['processed'], unique=False)
    op.create_index(op.f('ix_dark_funnel_signals_signal_type'), 'dark_funnel_signals', ['signal_type'], unique=False)
    op.create_table('dynamic_sequences',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('entry_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_sequences_id'), 'dynamic_sequences', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_sequences_name'), 'dynamic_sequences', ['name'], unique=True)
    op.create_index(op.f('ix_dynamic_sequences_signal_type'), 'dynamic_sequences', ['signal_type'], unique=False)
    op.create_index(op.f('ix_dynamic_sequences_status'), 'dynamic_sequences', ['status'], unique=False)
    op.create_table('failed_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('pending_action_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_task_id', sa.Uuid(), nullable=True),
    sa.Column('original_event', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_history', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ceo_alerted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_events_event_name'), 'failed_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_failed_events_event_type'), 'failed_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_failed_events_id'), 'failed_events', ['id'], unique=False)
    op.create_index(op.f('ix_failed_events_lead_id'), 'failed_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_failed_events_next_retry_at'), 'failed_events', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_failed_events_opportunity_id'), 'failed_events', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_failed_events_pending_action_id'), 'failed_events', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_failed_events_status'), 'failed_events', ['status'], unique=False)
    op.create_index(op.f('ix_failed_events_workflow_task_id'), 'failed_events', ['workflow_task_id'], unique=False)
    op.create_table('hot_lead_scores',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('research_intensity_score', sa.Float(), nullable=False),
    sa.Column('buying_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('signal_types_seen', sa.JSON(), nullable=True),
    sa.Column('top_intent_keywords', sa.JSON(), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('window_start_at', sa.DateTime(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('hot_since', sa.DateTime(), nullable=True),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hot_lead_scores_buying_stage'), 'hot_lead_scores', ['buying_stage'], unique=False)
    op.create_index(op.f('ix_hot_lead_scores_company_domain'), 'hot_lead_scores', ['company_domain'], unique=True)
    op.create_index(op.f('ix_hot_lead_scores_id'), 'hot_lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_hot_lead_scores_is_hot'), 'hot_lead_scores', ['is_hot'], unique=False)
    op.create_index(op.f('ix_hot_lead_scores_last_signal_at'), 'hot_lead_scores', ['last_signal_at'], unique=False)
    op.create_index(op.f('ix_hot_lead_scores_lead_id'), 'hot_lead_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_hot_lead_scores_research_intensity_score'), 'hot_lead_scores', ['research_intensity_score'], unique=False)
    op.create_table('incoming_engagement_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_post', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analysis_confidence', sa.Float(), nullable=False),
    sa.Column('analysis_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pending_action_id', sa.Uuid(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id')
    )
    op.create_index(op.f('ix_incoming_engagement_events_id'), 'incoming_engagement_events', ['id'], unique=False)
    op.create_index(op.f('ix_incoming_engagement_events_intent'), 'incoming_engagement_events', ['intent'], unique=False)
    op.create_index(op.f('ix_incoming_engagement_events_processed'), 'incoming_engagement_events', ['processed'], unique=False)
    op.create_index(op.f('ix_incoming_engagement_events_sentiment'), 'incoming_engagement_events', ['sentiment'], unique=False)
    op.create_index(op.f('ix_incoming_engagement_events_source'), 'incoming_engagement_events', ['source'], unique=False)
    op.create_table('lead_psychographics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('d_score', sa.Float(), nullable=False),
    sa.Column('i_score', sa.Float(), nullable=False),
    sa.Column('s_score', sa.Float(), nullable=False),
    sa.Column('c_score', sa.Float(), nullable=False),
    sa.Column('dominant_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classification_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_message_length', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avoid_phrases', sa.JSON(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_psychographics_dominant_style'), 'lead_psychographics', ['dominant_style'], unique=False)
    op.create_index(op.f('ix_lead_psychographics_id'), 'lead_psychographics', ['id'], unique=False)
    op.create_index(op.f('ix_lead_psychographics_lead_id'), 'lead_psychographics', ['lead_id'], unique=True)
    op.create_table('market_insights',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('insight_type', sa.Enum('VOLUME_SPIKE', 'SECTOR_MOMENTUM', 'EMERGING_PATTERN', 'COMPETITIVE_CLUSTER', 'SEASONAL_TREND', name='insighttype'), nullable=False),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tactical_implication', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_insights_expires_at'), 'market_insights', ['expires_at'], unique=False)
    op.create_index(op.f('ix_market_insights_id'), 'market_insights', ['id'], unique=False)
    op.create_index(op.f('ix_market_insights_industry'), 'market_insights', ['industry'], unique=False)
    op.create_index(op.f('ix_market_insights_insight_type'), 'market_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_market_insights_is_active'), 'market_insights', ['is_active'], unique=False)
    op.create_index(op.f('ix_market_insights_signal_type'), 'market_insights', ['signal_type'], unique=False)
    op.create_table('network_connections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship_strength', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mutual_connection_ids', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('last_interaction_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_connections_active'), 'network_connections', ['active'], unique=False)
    op.create_index(op.f('ix_network_connections_connection_type'), 'network_connections', ['connection_type'], unique=False)
    op.create_index(op.f('ix_network_connections_contact_company'), 'network_connections', ['contact_company'], unique=False)
    op.create_index(op.f('ix_network_connections_contact_domain'), 'network_connections', ['contact_domain'], unique=False)
    op.create_index(op.f('ix_network_connections_contact_name'), 'network_connections', ['contact_name'], unique=False)
    op.create_index(op.f('ix_network_connections_id'), 'network_connections', ['id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_bundle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_type', sa.Enum('SEND_EMAIL', 'BOOK_MEETING', 'CRM_UPDATE', 'SLACK_NOTIFY', 'LINKEDIN_MESSAGE', 'WEBHOOK_CALL', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'COMPLETED', 'FAILED', name='actionstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executing_tool', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_action_type'), 'pending_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_pending_actions_id'), 'pending_actions', ['id'], unique=False)
    op.create_index(op.f('ix_pending_actions_opportunity_id'), 'pending_actions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_priority'), 'pending_actions', ['priority'], unique=False)
    op.create_index(op.f('ix_pending_actions_status'), 'pending_actions', ['status'], unique=False)
    op.create_table('strategy_outcomes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('days_to_close', sa.Integer(), nullable=True),
    sa.Column('score_at_close', sa.Float(), nullable=False),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('cycle_days', sa.Integer(), nullable=True),
    sa.Column('playbook', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strategy_snapshot', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_outcomes_channel'), 'strategy_outcomes', ['channel'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_closed_at'), 'strategy_outcomes', ['closed_at'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_company_industry'), 'strategy_outcomes', ['company_industry'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_generator'), 'strategy_outcomes', ['generator'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_id'), 'strategy_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_industry'), 'strategy_outcomes', ['industry'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_lead_seniority'), 'strategy_outcomes', ['lead_seniority'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_opportunity_id'), 'strategy_outcomes', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_outcome'), 'strategy_outcomes', ['outcome'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_playbook'), 'strategy_outcomes', ['playbook'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_signal_id'), 'strategy_outcomes', ['signal_id'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_signal_type'), 'strategy_outcomes', ['signal_type'], unique=False)
    op.create_table('tactic_variants',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hypothesis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_a_config', sa.JSON(), nullable=True),
    sa.Column('arm_b_config', sa.JSON(), nullable=True),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('min_samples_per_arm', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CONCLUDED', name='variantstatus'), nullable=False),
    sa.Column('winner_arm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_a_wins', sa.Integer(), nullable=False),
    sa.Column('arm_a_total', sa.Integer(), nullable=False),
    sa.Column('arm_b_wins', sa.Integer(), nullable=False),
    sa.Column('arm_b_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactic_variants_id'), 'tactic_variants', ['id'], unique=False)
    op.create_index(op.f('ix_tactic_variants_industry'), 'tactic_variants', ['industry'], unique=False)
    op.create_index(op.f('ix_tactic_variants_name'), 'tactic_variants', ['name'], unique=False)
    op.create_index(op.f('ix_tactic_variants_signal_type'), 'tactic_variants', ['signal_type'], unique=False)
    op.create_index(op.f('ix_tactic_variants_status'), 'tactic_variants', ['status'], unique=False)
    op.create_table('user_style_profiles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('style_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_corrections', sa.Integer(), nullable=False),
    sa.Column('authoritative_rules_count', sa.Integer(), nullable=False),
    sa.Column('last_correction_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_style_profiles_id'), 'user_style_profiles', ['id'], unique=False)
    op.create_table('variant_outcomes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_outcome_id', sa.Uuid(), nullable=False),
    sa.Column('arm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_outcomes_strategy_outcome_id'), 'variant_outcomes', ['strategy_outcome_id'], unique=False)
    op.create_index(op.f('ix_variant_outcomes_variant_id'), 'variant_outcomes', ['variant_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone_descriptors', sa.JSON(), nullable=True),
    sa.Column('authority_topics', sa.JSON(), nullable=True),
    sa.Column('forbidden_phrases', sa.JSON(), nullable=True),
    sa.Column('max_sentence_words', sa.Integer(), nullable=False),
    sa.Column('use_emojis', sa.Boolean(), nullable=False),
    sa.Column('preferred_cta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio_summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_id'), 'voice_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_is_active'), 'voice_profiles', ['is_active'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('handler_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handler_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_entity_id'), 'workflow_tasks', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_event_type'), 'workflow_tasks', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_handler_name'), 'workflow_tasks', ['handler_name'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_status'), 'workflow_tasks', ['status'], unique=False)
    op.create_table('brand_fragments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('vector_doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_fragments_category'), 'brand_fragments', ['category'], unique=False)
    op.create_index(op.f('ix_brand_fragments_id'), 'brand_fragments', ['id'], unique=False)
    op.create_index(op.f('ix_brand_fragments_profile_id'), 'brand_fragments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_brand_fragments_vector_doc_id'), 'brand_fragments', ['vector_doc_id'], unique=True)
    op.create_table('leads',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'ENGAGED', 'CONVERTED', 'DISQUALIFIED', name='leadstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('data_freshness_score', sa.Float(), nullable=False),
    sa.Column('validation_flags', sa.JSON(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('stale_risk', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_seniority'), 'leads', ['seniority'], unique=False)
    op.create_index(op.f('ix_leads_stale_risk'), 'leads', ['stale_risk'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('sequence_executions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('current_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('pending_action_ids', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_advanced_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['dynamic_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_executions_id'), 'sequence_executions', ['id'], unique=False)
    op.create_index(op.f('ix_sequence_executions_lead_id'), 'sequence_executions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sequence_executions_opportunity_id'), 'sequence_executions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_sequence_executions_sequence_id'), 'sequence_executions', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_sequence_executions_status'), 'sequence_executions', ['status'], unique=False)
    op.create_table('signals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('signal_type', sa.Enum('FUNDING_ROUND', 'HIRING', 'TECH_ADOPTION', 'LEADERSHIP_CHANGE', 'PRODUCT_LAUNCH', 'ENGAGEMENT', 'NEWS_MENTION', 'EXPANSION', 'OTHER', name='signaltype'), nullable=False),
    sa.Column('source', sa.Enum('WEBHOOK', 'MANUAL', 'CRAWLER', 'CRM', 'ENRICHMENT', 'BEHAVIORAL', name='signalsource'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_detected_at'), 'signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_signals_external_id'), 'signals', ['external_id'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_lead_id'), 'signals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_signals_score'), 'signals', ['score'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_source'), 'signals', ['source'], unique=False)
    op.create_table('opportunities',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'READY_TO_ACTION', 'PRIORITIZED', 'IN_PROGRESS', 'WON', 'LOST', 'DISMISSED', name='opportunitystatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('execution_artifacts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_opportunities_score'), 'opportunities', ['score'], unique=False)
    op.create_index(op.f('ix_opportunities_signal_id'), 'opportunities', ['signal_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_signal_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_signals_source'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_score'), table_name='signals')
    op.drop_index(op.f('ix_signals_lead_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_external_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_detected_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sequence_executions_status'), table_name='sequence_executions')
    op.drop_index(op.f('ix_sequence_executions_sequence_id'), table_name='sequence_executions')
    op.drop_index(op.f('ix_sequence_executions_opportunity_id'), table_name='sequence_executions')
    op.drop_index(op.f('ix_sequence_executions_lead_id'), table_name='sequence_executions')
    op.drop_index(op.f('ix_sequence_executions_id'), table_name='sequence_executions')
    op.drop_table('sequence_executions')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_stale_risk'), table_name='leads')
    op.drop_index(op.f('ix_leads_seniority'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_brand_fragments_vector_doc_id'), table_name='brand_fragments')
    op.drop_index(op.f('ix_brand_fragments_profile_id'), table_name='brand_fragments')
    op.drop_index(op.f('ix_brand_fragments_id'), table_name='brand_fragments')
    op.drop_index(op.f('ix_brand_fragments_category'), table_name='brand_fragments')
    op.drop_table('brand_fragments')
    op.drop_index(op.f('ix_workflow_tasks_status'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_handler_name'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_event_type'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_entity_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_voice_profiles_is_active'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_variant_outcomes_variant_id'), table_name='variant_outcomes')
    op.drop_index(op.f('ix_variant_outcomes_strategy_outcome_id'), table_name='variant_outcomes')
    op.drop_table('variant_outcomes')
    op.drop_index(op.f('ix_user_style_profiles_id'), table_name='user_style_profiles')
    op.drop_table('user_style_profiles')
    op.drop_index(op.f('ix_tactic_variants_status'), table_name='tactic_variants')
    op.drop_index(op.f('ix_tactic_variants_signal_type'), table_name='tactic_variants')
    op.drop_index(op.f('ix_tactic_variants_name'), table_name='tactic_variants')
    op.drop_index(op.f('ix_tactic_variants_industry'), table_name='tactic_variants')
    op.drop_index(op.f('ix_tactic_variants_id'), table_name='tactic_variants')
    op.drop_table('tactic_variants')
    op.drop_index(op.f('ix_strategy_outcomes_signal_type'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_signal_id'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_playbook'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_outcome'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_opportunity_id'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_lead_seniority'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_industry'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_id'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_generator'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_company_industry'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_closed_at'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_channel'), table_name='strategy_outcomes')
    op.drop_table('strategy_outcomes')
    op.drop_index(op.f('ix_pending_actions_status'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_priority'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_opportunity_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_action_type'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_network_connections_id'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_contact_name'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_contact_domain'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_contact_company'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_connection_type'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_active'), table_name='network_connections')
    op.drop_table('network_connections')
    op.drop_index(op.f('ix_market_insights_signal_type'), table_name='market_insights')
    op.drop_index(op.f('ix_market_insights_is_active'), table_name='market_insights')
    op.drop_index(op.f('ix_market_insights_insight_type'), table_name='market_insights')
    op.drop_index(op.f('ix_market_insights_industry'), table_name='market_insights')
    op.drop_index(op.f('ix_market_insights_id'), table_name='market_insights')
    op.drop_index(op.f('ix_market_insights_expires_at'), table_name='market_insights')
    op.drop_table('market_insights')
    op.drop_index(op.f('ix_lead_psychographics_lead_id'), table_name='lead_psychographics')
    op.drop_index(op.f('ix_lead_psychographics_id'), table_name='lead_psychographics')
    op.drop_index(op.f('ix_lead_psychographics_dominant_style'), table_name='lead_psychographics')
    op.drop_table('lead_psychographics')
    op.drop_index(op.f('ix_incoming_engagement_events_source'), table_name='incoming_engagement_events')
    op.drop_index(op.f('ix_incoming_engagement_events_sentiment'), table_name='incoming_engagement_events')
    op.drop_index(op.f('ix_incoming_engagement_events_processed'), table_name='incoming_engagement_events')
    op.drop_index(op.f('ix_incoming_engagement_events_intent'), table_name='incoming_engagement_events')
    op.drop_index(op.f('ix_incoming_engagement_events_id'), table_name='incoming_engagement_events')
    op.drop_table('incoming_engagement_events')
    op.drop_index(op.f('ix_hot_lead_scores_research_intensity_score'), table_name='hot_lead_scores')
    op.drop_index(op.f('ix_hot_lead_scores_lead_id'), table_name='hot_lead_scores')
    op.drop_index(op.f('ix_hot_lead_scores_last_signal_at'), table_name='hot_lead_scores')
    op.drop_index(op.f('ix_hot_lead_scores_is_hot'), table_name='hot_lead_scores')
    op.drop_index(op.f('ix_hot_lead_scores_id'), table_name='hot_lead_scores')
    op.drop_index(op.f('ix_hot_lead_scores_company_domain'), table_name='hot_lead_scores')
    op.drop_index(op.f('ix_hot_lead_scores_buying_stage'), table_name='hot_lead_scores')
    op.drop_table('hot_lead_scores')
    op.drop_index(op.f('ix_failed_events_workflow_task_id'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_status'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_pending_action_id'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_opportunity_id'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_next_retry_at'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_lead_id'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_id'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_event_type'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_event_name'), table_name='failed_events')
    op.drop_table('failed_events')
    op.drop_index(op.f('ix_dynamic_sequences_status'), table_name='dynamic_sequences')
    op.drop_index(op.f('ix_dynamic_sequences_signal_type'), table_name='dynamic_sequences')
    op.drop_index(op.f('ix_dynamic_sequences_name'), table_name='dynamic_sequences')
    op.drop_index(op.f('ix_dynamic_sequences_id'), table_name='dynamic_sequences')
    op.drop_table('dynamic_sequences')
    op.drop_index(op.f('ix_dark_funnel_signals_signal_type'), table_name='dark_funnel_signals')
    op.drop_index(op.f('ix_dark_funnel_signals_processed'), table_name='dark_funnel_signals')
    op.drop_index(op.f('ix_dark_funnel_signals_lead_id'), table_name='dark_funnel_signals')
    op.drop_index(op.f('ix_dark_funnel_signals_id'), table_name='dark_funnel_signals')
    op.drop_index(op.f('ix_dark_funnel_signals_company_domain'), table_name='dark_funnel_signals')
    op.drop_table('dark_funnel_signals')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_entries_signal_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_session_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_pending_action_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_opportunity_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_manual_review_required'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_lead_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_decision_type'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_confidence_score'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_agent_type'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_artifact_corrections_opportunity_id'), table_name='artifact_corrections')
    op.drop_index(op.f('ix_artifact_corrections_lead_id'), table_name='artifact_corrections')
    op.drop_index(op.f('ix_artifact_corrections_id'), table_name='artifact_corrections')
    op.drop_index(op.f('ix_artifact_corrections_artifact_type'), table_name='artifact_corrections')
    op.drop_table('artifact_corrections')
    op.drop_index(op.f('ix_anomaly_alerts_status'), table_name='anomaly_alerts')
    op.drop_index(op.f('ix_anomaly_alerts_severity'), table_name='anomaly_alerts')
    op.drop_index(op.f('ix_anomaly_alerts_pending_action_id'), table_name='anomaly_alerts')
    op.drop_index(op.f('ix_anomaly_alerts_id'), table_name='anomaly_alerts')
    op.drop_index(op.f('ix_anomaly_alerts_alert_type'), table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for the native Postgres ENUM types
    # implicitly created by the sa.Enum(...) columns above (a shared enum type
    # could in principle back columns on more than one table, so autogenerate
    # never assumes it's safe to drop). Without this, downgrade() leaves the
    # types behind and a subsequent upgrade fails with
    # "type ... already exists" — confirmed by running this migration's
    # upgrade -> downgrade -> upgrade cycle end-to-end before landing it.
    for _enum_name in (
        "insighttype", "actiontype", "actionstatus", "variantstatus",
        "leadstatus", "signaltype", "signalsource", "opportunitystatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum_name}")
