"""Extension model tenant scoping.

Revision ID: 003_extension_tenant_scoping
Revises: 002_multi_tenant_auth
Create Date: 2026-08-23

Adds ``organization_id`` (nullable — same untagged-is-global convention as
migration 002) to every remaining model that lacked a tenant boundary:
``anomaly_alerts``, ``artifact_corrections``, ``audit_entries``,
``brand_fragments``, ``voice_profiles``, ``dark_funnel_signals``,
``hot_lead_scores``, ``dynamic_sequences``, ``sequence_executions``,
``failed_events``, ``incoming_engagement_events``, ``lead_psychographics``,
``market_insights``, ``network_connections``, ``pending_actions``,
``strategy_outcomes``, ``tactic_variants``, ``user_style_profiles``,
``workflow_tasks``.

Also fixes three dedup keys that were global instead of per-tenant — two
organizations legitimately tracking the same company domain, or each wanting
their own "Standard Onboarding" sequence, previously collided on one shared
row:

* ``companies.domain`` — was globally unique, now unique per
  ``(organization_id, domain)`` via ``uq_companies_org_domain``.
* ``dynamic_sequences.name`` — was globally unique, now unique per
  ``(organization_id, name)`` via ``uq_dynamic_sequences_org_name``.
* ``hot_lead_scores.company_domain`` — was globally unique, now unique per
  ``(organization_id, company_domain)`` via ``uq_hot_lead_scores_org_domain``.

Generated via ``alembic revision --autogenerate``, then hand-edited to name
every foreign key constraint explicitly (same anonymous-FK gap as migrations
000/002 — `op.drop_constraint(None, ...)` is not valid). Verified
upgrade -> downgrade -> upgrade end-to-end against a real Postgres instance
before landing.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003_extension_tenant_scoping"
down_revision: str | None = "002_multi_tenant_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anomaly_alerts", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_anomaly_alerts_organization_id"),
        "anomaly_alerts",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_anomaly_alerts_organization_id",
        "anomaly_alerts",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("artifact_corrections", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_artifact_corrections_organization_id"),
        "artifact_corrections",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_artifact_corrections_organization_id",
        "artifact_corrections",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("audit_entries", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_audit_entries_organization_id"), "audit_entries", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        "fk_audit_entries_organization_id",
        "audit_entries",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("brand_fragments", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_brand_fragments_organization_id"),
        "brand_fragments",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_brand_fragments_organization_id",
        "brand_fragments",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_companies_domain"), table_name="companies")
    op.create_index(op.f("ix_companies_domain"), "companies", ["domain"], unique=False)
    op.create_unique_constraint(
        "uq_companies_org_domain", "companies", ["organization_id", "domain"]
    )
    op.add_column("dark_funnel_signals", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_dark_funnel_signals_organization_id"),
        "dark_funnel_signals",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_dark_funnel_signals_organization_id",
        "dark_funnel_signals",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("dynamic_sequences", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.drop_index(op.f("ix_dynamic_sequences_name"), table_name="dynamic_sequences")
    op.create_index(op.f("ix_dynamic_sequences_name"), "dynamic_sequences", ["name"], unique=False)
    op.create_index(
        op.f("ix_dynamic_sequences_organization_id"),
        "dynamic_sequences",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_dynamic_sequences_org_name", "dynamic_sequences", ["organization_id", "name"]
    )
    op.create_foreign_key(
        "fk_dynamic_sequences_organization_id",
        "dynamic_sequences",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("failed_events", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_failed_events_organization_id"), "failed_events", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        "fk_failed_events_organization_id",
        "failed_events",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("hot_lead_scores", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.drop_index(op.f("ix_hot_lead_scores_company_domain"), table_name="hot_lead_scores")
    op.create_index(
        op.f("ix_hot_lead_scores_company_domain"),
        "hot_lead_scores",
        ["company_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hot_lead_scores_organization_id"),
        "hot_lead_scores",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_hot_lead_scores_org_domain", "hot_lead_scores", ["organization_id", "company_domain"]
    )
    op.create_foreign_key(
        "fk_hot_lead_scores_organization_id",
        "hot_lead_scores",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column(
        "incoming_engagement_events", sa.Column("organization_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_incoming_engagement_events_organization_id"),
        "incoming_engagement_events",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_incoming_engagement_events_organization_id",
        "incoming_engagement_events",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("lead_psychographics", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_lead_psychographics_organization_id"),
        "lead_psychographics",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_lead_psychographics_organization_id",
        "lead_psychographics",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("market_insights", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_market_insights_organization_id"),
        "market_insights",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_market_insights_organization_id",
        "market_insights",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("network_connections", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_network_connections_organization_id"),
        "network_connections",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_network_connections_organization_id",
        "network_connections",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("pending_actions", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_pending_actions_organization_id"),
        "pending_actions",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_pending_actions_organization_id",
        "pending_actions",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("sequence_executions", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_sequence_executions_organization_id"),
        "sequence_executions",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_sequence_executions_organization_id",
        "sequence_executions",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("strategy_outcomes", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_strategy_outcomes_organization_id"),
        "strategy_outcomes",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_strategy_outcomes_organization_id",
        "strategy_outcomes",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("tactic_variants", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_tactic_variants_organization_id"),
        "tactic_variants",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_tactic_variants_organization_id",
        "tactic_variants",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("user_style_profiles", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_user_style_profiles_organization_id"),
        "user_style_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_user_style_profiles_organization_id",
        "user_style_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("voice_profiles", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_voice_profiles_organization_id"),
        "voice_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_voice_profiles_organization_id",
        "voice_profiles",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.add_column("workflow_tasks", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_workflow_tasks_organization_id"),
        "workflow_tasks",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_workflow_tasks_organization_id",
        "workflow_tasks",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workflow_tasks_organization_id", "workflow_tasks", type_="foreignkey")
    op.drop_index(op.f("ix_workflow_tasks_organization_id"), table_name="workflow_tasks")
    op.drop_column("workflow_tasks", "organization_id")
    op.drop_constraint("fk_voice_profiles_organization_id", "voice_profiles", type_="foreignkey")
    op.drop_index(op.f("ix_voice_profiles_organization_id"), table_name="voice_profiles")
    op.drop_column("voice_profiles", "organization_id")
    op.drop_constraint(
        "fk_user_style_profiles_organization_id", "user_style_profiles", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_style_profiles_organization_id"), table_name="user_style_profiles")
    op.drop_column("user_style_profiles", "organization_id")
    op.drop_constraint("fk_tactic_variants_organization_id", "tactic_variants", type_="foreignkey")
    op.drop_index(op.f("ix_tactic_variants_organization_id"), table_name="tactic_variants")
    op.drop_column("tactic_variants", "organization_id")
    op.drop_constraint(
        "fk_strategy_outcomes_organization_id", "strategy_outcomes", type_="foreignkey"
    )
    op.drop_index(op.f("ix_strategy_outcomes_organization_id"), table_name="strategy_outcomes")
    op.drop_column("strategy_outcomes", "organization_id")
    op.drop_constraint(
        "fk_sequence_executions_organization_id", "sequence_executions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_sequence_executions_organization_id"), table_name="sequence_executions")
    op.drop_column("sequence_executions", "organization_id")
    op.drop_constraint("fk_pending_actions_organization_id", "pending_actions", type_="foreignkey")
    op.drop_index(op.f("ix_pending_actions_organization_id"), table_name="pending_actions")
    op.drop_column("pending_actions", "organization_id")
    op.drop_constraint(
        "fk_network_connections_organization_id", "network_connections", type_="foreignkey"
    )
    op.drop_index(op.f("ix_network_connections_organization_id"), table_name="network_connections")
    op.drop_column("network_connections", "organization_id")
    op.drop_constraint("fk_market_insights_organization_id", "market_insights", type_="foreignkey")
    op.drop_index(op.f("ix_market_insights_organization_id"), table_name="market_insights")
    op.drop_column("market_insights", "organization_id")
    op.drop_constraint(
        "fk_lead_psychographics_organization_id", "lead_psychographics", type_="foreignkey"
    )
    op.drop_index(op.f("ix_lead_psychographics_organization_id"), table_name="lead_psychographics")
    op.drop_column("lead_psychographics", "organization_id")
    op.drop_constraint(
        "fk_incoming_engagement_events_organization_id",
        "incoming_engagement_events",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_incoming_engagement_events_organization_id"),
        table_name="incoming_engagement_events",
    )
    op.drop_column("incoming_engagement_events", "organization_id")
    op.drop_constraint("fk_hot_lead_scores_organization_id", "hot_lead_scores", type_="foreignkey")
    op.drop_constraint("uq_hot_lead_scores_org_domain", "hot_lead_scores", type_="unique")
    op.drop_index(op.f("ix_hot_lead_scores_organization_id"), table_name="hot_lead_scores")
    op.drop_index(op.f("ix_hot_lead_scores_company_domain"), table_name="hot_lead_scores")
    op.create_index(
        op.f("ix_hot_lead_scores_company_domain"),
        "hot_lead_scores",
        ["company_domain"],
        unique=True,
    )
    op.drop_column("hot_lead_scores", "organization_id")
    op.drop_constraint("fk_failed_events_organization_id", "failed_events", type_="foreignkey")
    op.drop_index(op.f("ix_failed_events_organization_id"), table_name="failed_events")
    op.drop_column("failed_events", "organization_id")
    op.drop_constraint(
        "fk_dynamic_sequences_organization_id", "dynamic_sequences", type_="foreignkey"
    )
    op.drop_constraint("uq_dynamic_sequences_org_name", "dynamic_sequences", type_="unique")
    op.drop_index(op.f("ix_dynamic_sequences_organization_id"), table_name="dynamic_sequences")
    op.drop_index(op.f("ix_dynamic_sequences_name"), table_name="dynamic_sequences")
    op.create_index(op.f("ix_dynamic_sequences_name"), "dynamic_sequences", ["name"], unique=True)
    op.drop_column("dynamic_sequences", "organization_id")
    op.drop_constraint(
        "fk_dark_funnel_signals_organization_id", "dark_funnel_signals", type_="foreignkey"
    )
    op.drop_index(op.f("ix_dark_funnel_signals_organization_id"), table_name="dark_funnel_signals")
    op.drop_column("dark_funnel_signals", "organization_id")
    op.drop_constraint("uq_companies_org_domain", "companies", type_="unique")
    op.drop_index(op.f("ix_companies_domain"), table_name="companies")
    op.create_index(op.f("ix_companies_domain"), "companies", ["domain"], unique=True)
    op.drop_constraint("fk_brand_fragments_organization_id", "brand_fragments", type_="foreignkey")
    op.drop_index(op.f("ix_brand_fragments_organization_id"), table_name="brand_fragments")
    op.drop_column("brand_fragments", "organization_id")
    op.drop_constraint("fk_audit_entries_organization_id", "audit_entries", type_="foreignkey")
    op.drop_index(op.f("ix_audit_entries_organization_id"), table_name="audit_entries")
    op.drop_column("audit_entries", "organization_id")
    op.drop_constraint(
        "fk_artifact_corrections_organization_id", "artifact_corrections", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_artifact_corrections_organization_id"), table_name="artifact_corrections"
    )
    op.drop_column("artifact_corrections", "organization_id")
    op.drop_constraint("fk_anomaly_alerts_organization_id", "anomaly_alerts", type_="foreignkey")
    op.drop_index(op.f("ix_anomaly_alerts_organization_id"), table_name="anomaly_alerts")
    op.drop_column("anomaly_alerts", "organization_id")
    # ### end Alembic commands ###
