"""Organization API keys.

Revision ID: 004_organization_api_keys
Revises: 003_extension_tenant_scoping
Create Date: 2026-08-23

Adds ``organization_api_keys`` — per-tenant credentials for
``POST /signals/webhook`` and the BehavioralCollector (``/signals/intent``)
callers, which push data without a logged-in dashboard user and so need a
different way to identify their organization (an ``X-BEE-Org-Key`` header —
see ``app.api.deps.get_organization_from_api_key``). See
``app.models.organization_api_key`` for the full rationale.

A single-statement ``create_table``, so — unlike migrations 002/003 — there's
no anonymous-FK-naming gap to fix by hand: that issue only affects
``op.create_foreign_key``/``op.drop_constraint`` pairs adding a constraint to
an *existing* table, not FKs declared inline on table creation, where
``downgrade()`` simply drops the whole table.
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004_organization_api_keys"
down_revision: str | None = "003_extension_tenant_scoping"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_api_keys",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_api_keys_id"), "organization_api_keys", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_api_keys_is_active"),
        "organization_api_keys",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_api_keys_key_hash"),
        "organization_api_keys",
        ["key_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_organization_api_keys_organization_id"),
        "organization_api_keys",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_organization_api_keys_organization_id"), table_name="organization_api_keys"
    )
    op.drop_index(op.f("ix_organization_api_keys_key_hash"), table_name="organization_api_keys")
    op.drop_index(op.f("ix_organization_api_keys_is_active"), table_name="organization_api_keys")
    op.drop_index(op.f("ix_organization_api_keys_id"), table_name="organization_api_keys")
    op.drop_table("organization_api_keys")
    # ### end Alembic commands ###
