/**
 * Round-number milestones for a rep's (or team's) real total of won
 * deals — starting with the very first close (1), then a nearby early
 * one (5) so a brand-new rep has something to reach almost immediately,
 * then the classic 1-2-5 sequence from 10 on (10, 20, 50, 100, 200, 500,
 * 1000, 2000, 5000…). Generated by a formula rather than a hardcoded
 * array, so it has no end no matter how large a rep's history grows.
 * Shared by the milestone-crossed celebration
 * (use-milestone-celebration.ts) and the milestone path
 * (milestone-path.tsx), so the two always agree on what a "level" is.
 */
const PREFIX = [1, 5] as const;
const PATTERN = [1, 2, 5] as const;

export function milestoneAt(index: number): number {
  if (index < PREFIX.length) return PREFIX[index];
  const i = index - PREFIX.length;
  const decade = Math.floor(i / PATTERN.length);
  return PATTERN[i % PATTERN.length] * 10 ** (decade + 1);
}

/** The index of the smallest milestone >= total — "the next one to reach",
 * or the one just reached if total lands exactly on it. */
export function currentMilestoneIndex(total: number): number {
  let i = 0;
  while (milestoneAt(i) < total) i++;
  return i;
}
