/**
 * Round-number milestones for the team's real total of won deals — the
 * classic 1-2-5 sequence (10, 20, 50, 100, 200, 500, 1000, 2000, 5000…),
 * generated by a formula rather than a hardcoded array, so it has no end
 * no matter how large a team's history grows. Shared by the
 * milestone-crossed celebration (use-milestone-celebration.ts) and the
 * infinite path card (milestone-path-card.tsx), so the two always agree
 * on what a "level" is.
 */
const PATTERN = [1, 2, 5] as const;

export function milestoneAt(index: number): number {
  const decade = Math.floor(index / PATTERN.length);
  return PATTERN[index % PATTERN.length] * 10 ** (decade + 1);
}

/** The index of the smallest milestone >= total — "the next one to reach",
 * or the one just reached if total lands exactly on it. */
export function currentMilestoneIndex(total: number): number {
  let i = 0;
  while (milestoneAt(i) < total) i++;
  return i;
}
